### ISSUE TITLE
Feature: xtts generation parameters like temperature, top_k, etc

### ISSUE THREAD

**Issue by matatonic** [matatonic/openedai-speech#22]
to be set on a per voice basis. 

Proposed format:

```yaml
sky:
  model: xtts
  speaker: voices/sky.wav
  generation_params:
    temperature: 0.7
    repetition_penalty: 5.0
```
