### ISSUE TITLE
Custom piper voice generates empty mp3

### ISSUE THREAD

**Issue by nocaremc** [matatonic/openedai-speech#27]
I trained a onnx model with piper. Tested and working well.
When adding to openedai-speech as a speaker, I just get an empty mp3

voice_to_speaker.yml
``` yaml 
nocare:
    model: voices/en_US-nocare-medium.onnx
    speaker: # default
```
![image](https://github.com/matatonic/openedai-speech/assets/3071777/2cbfc86d-71ab-47eb-bf8f-397cb77c42f8)

```
curl http://localhost:8000/v1/audio/speech -H "Content-Type: application/json" -d '{
    "model": "tts-1",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "nocare",
    "response_format": "mp3",
    "speed": 1.0
  }' > speech.mp3

```

I'm using the non-gpu docker image and I'm not really sure where I can find any kind of log output. Any help is appreciated
