### ISSUE TITLE
v0.17.3 - No module named 'yaml'

### ISSUE THREAD

**Issue by silentoplayz** [matatonic/openedai-speech#42]
https://github.com/matatonic/openedai-speech/commit/b5d0dafd7d95a1431e598835b4af9ab1949fb91f

I now get this error that causes openedai-speech to restart over and over within Docker desktop:
```
Traceback (most recent call last):
File "/app/speech.py", line 12, in <module>
import yaml
ModuleNotFoundError: No module named 'yaml'
```

Here's how I have incorporated opendai-speech into a docker-compose.yml file (with other services):

```yaml
services:
  openedai-speech-min:
    image: ghcr.io/matatonic/openedai-speech-min
    container_name: openedai-speech-min
    ports:
      - "8000:8000"
    env_file:
      - openedai-speech-min.env
    volumes:
      - .tts-voices:/app/voices # bind mount
      - .tts-config:/app/config # bind mount
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
 ```

openedai-speech-min.env:
```
# Openedai-speech
TTS_HOME=voices
HF_HOME=voices
#PRELOAD_MODEL=xtts
#PRELOAD_MODEL=xtts_v2.0.2
#PRELOAD_MODEL=parler-tts/parler_tts_mini_v0.1
```
