### ISSUE TITLE
Error loading user defined voice

### ISSUE THREAD

**Issue by 4383** [matatonic/openedai-speech#81]
Hey folks,

Firstly, thanks for this nice project.

I face problems with a voice I created.
Indeed, I [followed your instructions to create a Coqui XTTS v2 based voice](https://github.com/matatonic/openedai-speech?tab=readme-ov-file#coqui-xtts-v2), but when I try to use it I face the following error:

```
server-1  | INFO:     172.25.0.1:41728 - "POST /v1/audio/speech HTTP/1.1" 400 Bad Request
server-1  | 2024-12-11 10:52:30.679 | INFO     | openedai:openai_statuserror_handler:106 - BadRequestError(message="Error loading voice: myvoice, KeyError: 'myvoice'", code=400, param=voice)
server-1  | INFO:     172.25.0.1:55108 - "POST /v1/audio/speech HTTP/1.1" 400 Bad Request
```

Here is an extracted sample of my `config/voice_to_speaker.yaml`:

```yaml
tts-1-hd:                                                                                                                                                      
  myvoice:                                                                                                                                                     
    model: xtts                                                                                                                                                
    speaker: voices/myvoice.wav                                                                                                                                
  alloy-alt:                                                                                                                                                   
    model: xtts                                                                                                                                                
    speaker: voices/alloy-alt.wav    
```

You can observe that I create a `myvoice` entry under the `tts-1-hd` model.

Here is a list overview of my `voices` directory:

```bash
ls -la voices | grep wav
-rw-r--r--. 1 hberaud hberaud   501020  2 déc.  14:27 alloy-alt.wav
-rw-r--r--. 1 root    root      307014 11 déc.  11:30 alloy.wav
-rw-r--r--. 1 root    root      394862 11 déc.  11:30 echo.wav
-rw-r--r--. 1 root    root      402270 11 déc.  11:30 fable.wav
-rw-r--r--. 1 hberaud hberaud   264678 11 déc.  11:02 myvoice.wav
-rw-r--r--. 1 root    root      409680 11 déc.  11:30 nova.wav
-rw-r--r--. 1 root    root      381102 11 déc.  11:30 onyx.wav
-rw-r--r--. 1 root    root      373694 11 déc.  11:30 shimmer.wav
```

Here is the ffmpeg command I ran:

```
$ ffmpeg -i myvoice.mp3 -ac 1 -ar 22050 -t 6 -y myvoice.wav
```

Here is how I run my environment:

```bash
$ docker compose -f docker-compose.min.yml build
$ docker compose -f docker-compose.min.yml up
```

If I jump into my running container, I can find my wav file and the config seems ok.

And here is how I call the API:

```
curl http://localhost:8000/v1/audio/speech -H "Content-Type: application/json" -d '{
    "model": "tts-1-hd",
    "input": "Bonjour à tous",
    "voice": "myvoice",
    "response_format": "mp3",
    "speed": 0.9
  }' > ~/myvoice.mp3
```

I tried this command with other voices and the mp3 file created is successfully created and valid.

Did i forget something that could explain my problem?
I don't understand why the voice is not find. Does that mean that the wav file is not found or that the target is not find in the yaml config file?
