### ISSUE TITLE
Cannot get custom voices to work. Always 404. Works with preinstalled voices only. Please help :)

### ISSUE THREAD

**Issue by praul** [matatonic/openedai-speech#89]
Hi there, I am really trying to make this work with openwebui. However, I cannot get custom voices to work. 

1. It works with preinstalled voices (for example en_GB-northern_english_male-medium.onnx)
2. I installed custom voices with download_voices_tts-1.sh
3. I adjusted voice_to_speaker.yaml
4. Models were correctly downloaded and sit happily in voices folder

When requesting speech with custom voice, openedai-speech always gives 404s.
I tried fiddling with different parameters in voice_to_speaker.yaml but with no success.
Please help me :)

Log:
```
openedai-speech-1  | 2025-01-25 10:59:50.857 | DEBUG    | openedai:log_requests:120 - Request path: /audio/speech
openedai-speech-1  | 2025-01-25 10:59:50.858 | DEBUG    | openedai:log_requests:121 - Request method: POST
openedai-speech-1  | 2025-01-25 10:59:50.858 | DEBUG    | openedai:log_requests:122 - Request headers: Headers({'host': 'openedai-speech:8000', 'content-type': 'application/json', 'authorization': 'Bearer your_api_key_here', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'user-agent': 'Python/3.11 aiohttp/3.11.8', 'content-length': '102'})
openedai-speech-1  | 2025-01-25 10:59:50.858 | DEBUG    | openedai:log_requests:123 - Request query params:
openedai-speech-1  | 2025-01-25 10:59:50.859 | DEBUG    | openedai:log_requests:124 - Request body: b'{"input": "Dies ist ein Testprompt f\\u00fcr die Sprachausgabe", "voice": "thorsten", "model": "tts-1"}'
openedai-speech-1  | 2025-01-25 10:59:50.860 | DEBUG    | openedai:log_requests:128 - Response status code: 404
openedai-speech-1  | 2025-01-25 10:59:50.860 | DEBUG    | openedai:log_requests:129 - Response headers: MutableHeaders({'content-length': '22', 'content-type': 'application/json'})
openedai-speech-1  | INFO:     172.18.0.3:54336 - "POST /audio/speech HTTP/1.1" 404 Not Found
```

voice_to_speaker.yaml (excerpt):
```
tts-1:
  thorsten:
    model: de_DE-thorsten-medium
    model_path: voices/de_DE-thorsten-medium.onnx
    speaker: #
    language: DE
```

voices folder:
```
/home/ai/docker-compose/gpu_openwebui/data/openedaispeech/voices# ls -la
insgesamt 185296
drwxr-xr-x 2 root root     4096 Jan 22 13:50 .
drwxr-xr-x 4 root root     4096 Jan 22 10:46 ..
-rw-r--r-- 1 root root 63201294 Jan 22 13:35 de_DE-thorsten-medium.onnx
-rw-r--r-- 1 root root     4819 Jan 22 13:35 de_DE-thorsten-medium.onnx.json
-rw-r--r-- 1 root root 63201294 Jan 22 10:46 en_GB-northern_english_male-medium.onnx
-rw-r--r-- 1 root root     4847 Jan 22 10:46 en_GB-northern_english_male-medium.onnx.json
-rw-r--r-- 1 root root 63104526 Jan 22 11:01 en_US-libritts_r-medium.onnx
-rw-r--r-- 1 root root     4159 Jan 22 11:01 en_US-libritts_r-medium.onnx.json
-rw-r--r-- 1 root root   190552 Jan 25 11:55 voices.json
```

docker-compose (part)
```
openedai-speech:
        image: ghcr.io/matatonic/openedai-speech-min
        env_file: speech.env
        volumes:
            - ./data/openedaispeech/voices:/app/voices
            - ./data/openedaispeech/config:/app/config
```

Trying self-built docker image now...
